import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="absher-header">
          <div className="container" style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between'}}>
            <div style={{display:'flex', alignItems:'center', gap:12}}>
              <div className="brand">أبشر - Demo</div>
            </div>
            <nav className="absher-muted" style={{fontSize:14}}>
              <span style={{marginLeft:12}}>المنصة</span>
              <span style={{marginLeft:12}}>الخدمات</span>
            </nav>
          </div>
        </header>

        <img
          src="https://sl.bing.net/hsmsL5wv3v2"
          alt="background"
          className="bg-bottom-image"
        />

        <div className="app-content">
          <main className="container">{children}</main>
        </div>
      </body>
    </html>
  );
}
